### ISSUE TITLE
标题栏“Android多语言”怎么使他同步国际化

### ISSUE THREAD

**Issue by gnmmdk** [finddreams/AndroidMultiLanguage#1]
标题栏“Android多语言”怎么使他同步国际化

**Comment by finddreams** [comment]
在oncreate 中设置一下setTitle()就行了
`   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_web_view);
        setTitle(R.string.app_name);
}`

**Comment by gnmmdk** [comment]
这个我知道，您在代码就是这样设置了。只不过这样设置，国际化的时候，没效果！

**Comment by finddreams** [comment]
不是没效果是有些页面没有写setTitle()，更新了代码，现在应该是都会跟着变了。

**Comment by gnmmdk** [comment]
了解了，谢谢！
