### ISSUE TITLE
语言切换必须要杀掉中间界面？

### ISSUE THREAD

**Issue by xiaotianchang** [finddreams/AndroidMultiLanguage#6]
hello，用了你的demo,就是跟自己的项目需求有点出入，因为设置语言切换是在设置界面里面的，切换完语言需要能返回到之前打开的页面而且显示的语言需要是切换过后的语言，你的demo中是必须要杀掉中间的页面重新生成界面的回到主入口去，请问有优化方法吗

**Comment by ZhangDream** [comment]
同问，问一下你解决了没

**Comment by finddreams** [comment]
@xiaotianchang @ZhangDream 多语言切换 目前主流的APP都是杀掉中间页的

**Comment by ZhangDream** [comment]
> @xiaotianchang @ZhangDream 多语言切换 目前主流的APP都是杀掉中间页的

好的 多谢
